export const ADD_APPLICATION = "ADD_APPLICATION";
export const EDIT_APPLICATION = "EDIT_APPLICATION";
export const EDIT_STATUS_APPLICATION = "EDIT_STATUS_APPLICATION";
export const EDIT_ACCOUNT = "EDIT_ACCOUNT";
export const DELETE_ACCOUNT = "DELETE_ACCOUNT";

export const REQUEST_TODOS = "REQUEST_TODOS";
export const REQUEST_TODOS_SUCCESS = "REQUEST_TODOS_SUCCESS";
export const REQUEST_TODOS_ERROR = "REQUEST_TODOS_ERROR";
